// All IDs verified directly from football-data.org API
const BASE = "https://crests.football-data.org";

const CRESTS = {
  // ── La Liga ─────────────────────────────────────────────────────
  "Athletic Club": `${BASE}/77.png`,
  "Athletic Bilbao": `${BASE}/77.png`,
  "Club Atlético de Madrid": `${BASE}/78.png`,
  "Atlético de Madrid": `${BASE}/78.png`,
  "Atletico de Madrid": `${BASE}/78.png`,
  "Atletico Madrid": `${BASE}/78.png`,
  "CA Osasuna": `${BASE}/79.png`,
  "Osasuna": `${BASE}/79.png`,
  "RCD Espanyol de Barcelona": `${BASE}/80.png`,
  "RCD Espanyol": `${BASE}/80.png`,
  "Espanyol": `${BASE}/80.png`,
  "FC Barcelona": `${BASE}/81.png`,
  "Barcelona": `${BASE}/81.png`,
  "Getafe CF": `${BASE}/82.png`,
  "Getafe": `${BASE}/82.png`,
  "Real Madrid CF": `${BASE}/86.png`,
  "Real Madrid": `${BASE}/86.png`,
  "Rayo Vallecano de Madrid": `${BASE}/87.png`,
  "Rayo Vallecano": `${BASE}/87.png`,
  "Levante UD": `${BASE}/88.png`,
  "Levante": `${BASE}/88.png`,
  "RCD Mallorca": `${BASE}/89.png`,
  "Mallorca": `${BASE}/89.png`,
  "Real Betis Balompié": `${BASE}/90.png`,
  "Real Betis": `${BASE}/90.png`,
  "Real Sociedad de Fútbol": `${BASE}/92.png`,
  "Real Sociedad": `${BASE}/92.png`,
  "Villarreal CF": `${BASE}/94.png`,
  "Villarreal": `${BASE}/94.png`,
  "Valencia CF": `${BASE}/95.png`,
  "Valencia": `${BASE}/95.png`,
  "Real Valladolid CF": `${BASE}/250.png`,
  "Real Valladolid": `${BASE}/250.png`,
  "Deportivo Alavés": `${BASE}/263.png`,
  "Alavés": `${BASE}/263.png`,
  "Alaves": `${BASE}/263.png`,
  "UD Las Palmas": `${BASE}/275.png`,
  "Las Palmas": `${BASE}/275.png`,
  "Elche CF": `${BASE}/285.png`,
  "Elche": `${BASE}/285.png`,
  "Girona FC": `${BASE}/298.png`,
  "Girona": `${BASE}/298.png`,
  "RC Celta de Vigo": `${BASE}/558.png`,
  "Celta de Vigo": `${BASE}/558.png`,
  "Celta Vigo": `${BASE}/558.png`,
  "Sevilla FC": `${BASE}/559.png`,
  "Sevilla": `${BASE}/559.png`,
  "CD Leganés": `${BASE}/745.png`,
  "Leganés": `${BASE}/745.png`,
  "Leganes": `${BASE}/745.png`,
  "Real Oviedo": `${BASE}/1048.png`,
  // ── Premier League ──────────────────────────────────────────────
  "Arsenal FC": `${BASE}/57.png`,
  "Arsenal": `${BASE}/57.png`,
  "Aston Villa FC": `${BASE}/58.png`,
  "Aston Villa": `${BASE}/58.png`,
  "Chelsea FC": `${BASE}/61.png`,
  "Chelsea": `${BASE}/61.png`,
  "Everton FC": `${BASE}/62.png`,
  "Everton": `${BASE}/62.png`,
  "Fulham FC": `${BASE}/63.png`,
  "Fulham": `${BASE}/63.png`,
  "Liverpool FC": `${BASE}/64.png`,
  "Liverpool": `${BASE}/64.png`,
  "Manchester City FC": `${BASE}/65.png`,
  "Manchester City": `${BASE}/65.png`,
  "Manchester United FC": `${BASE}/66.png`,
  "Manchester United": `${BASE}/66.png`,
  "Newcastle United FC": `${BASE}/67.png`,
  "Newcastle United": `${BASE}/67.png`,
  "Newcastle": `${BASE}/67.png`,
  "Sunderland AFC": `${BASE}/71.png`,
  "Sunderland": `${BASE}/71.png`,
  "Tottenham Hotspur FC": `${BASE}/73.png`,
  "Tottenham Hotspur": `${BASE}/73.png`,
  "Tottenham": `${BASE}/73.png`,
  "Wolverhampton Wanderers FC": `${BASE}/76.png`,
  "Wolverhampton Wanderers": `${BASE}/76.png`,
  "Wolverhampton": `${BASE}/76.png`,
  "Wolves": `${BASE}/76.png`,
  "Burnley FC": `${BASE}/328.png`,
  "Burnley": `${BASE}/328.png`,
  "Leicester City FC": `${BASE}/338.png`,
  "Leicester City": `${BASE}/338.png`,
  "Leicester": `${BASE}/338.png`,
  "Southampton FC": `${BASE}/340.png`,
  "Southampton": `${BASE}/340.png`,
  "Ipswich Town FC": `${BASE}/349.png`,
  "Ipswich Town": `${BASE}/349.png`,
  "Nottingham Forest FC": `${BASE}/351.png`,
  "Nottingham Forest": `${BASE}/351.png`,
  "Crystal Palace FC": `${BASE}/354.png`,
  "Crystal Palace": `${BASE}/354.png`,
  "Brighton & Hove Albion FC": `${BASE}/397.png`,
  "Brighton & Hove Albion": `${BASE}/397.png`,
  "Brighton": `${BASE}/397.png`,
  "Brentford FC": `${BASE}/402.png`,
  "Brentford": `${BASE}/402.png`,
  "West Ham United FC": `${BASE}/563.png`,
  "West Ham United": `${BASE}/563.png`,
  "West Ham": `${BASE}/563.png`,
  "Leeds United FC": `${BASE}/341.png`,
  "Leeds United": `${BASE}/341.png`,
  "AFC Bournemouth": `${BASE}/1044.png`,
  "Bournemouth": `${BASE}/1044.png`,
  // ── Bundesliga ──────────────────────────────────────────────────
  "1. FC Köln": `${BASE}/1.png`,
  "Köln": `${BASE}/1.png`,
  "TSG 1899 Hoffenheim": `${BASE}/2.png`,
  "TSG Hoffenheim": `${BASE}/2.png`,
  "Hoffenheim": `${BASE}/2.png`,
  "Bayer 04 Leverkusen": `${BASE}/3.png`,
  "Bayer Leverkusen": `${BASE}/3.png`,
  "Borussia Dortmund": `${BASE}/4.png`,
  "BVB Dortmund": `${BASE}/4.png`,
  "FC Bayern München": `${BASE}/5.png`,
  "Bayern München": `${BASE}/5.png`,
  "Bayern Munich": `${BASE}/5.png`,
  "Hamburger SV": `${BASE}/7.png`,
  "HSV": `${BASE}/7.png`,
  "VfB Stuttgart": `${BASE}/10.png`,
  "Stuttgart": `${BASE}/10.png`,
  "VfL Wolfsburg": `${BASE}/11.png`,
  "Wolfsburg": `${BASE}/11.png`,
  "SV Werder Bremen": `${BASE}/12.png`,
  "Werder Bremen": `${BASE}/12.png`,
  "1. FSV Mainz 05": `${BASE}/15.png`,
  "Mainz 05": `${BASE}/15.png`,
  "Mainz": `${BASE}/15.png`,
  "FC Augsburg": `${BASE}/16.png`,
  "Augsburg": `${BASE}/16.png`,
  "SC Freiburg": `${BASE}/17.png`,
  "Freiburg": `${BASE}/17.png`,
  "Borussia Mönchengladbach": `${BASE}/18.png`,
  "Borussia M'gladbach": `${BASE}/18.png`,
  "Eintracht Frankfurt": `${BASE}/19.png`,
  "FC St. Pauli 1910": `${BASE}/20.png`,
  "FC St. Pauli": `${BASE}/20.png`,
  "St. Pauli": `${BASE}/20.png`,
  "1. FC Union Berlin": `${BASE}/28.png`,
  "Union Berlin": `${BASE}/28.png`,
  "VfL Bochum 1848": `${BASE}/36.png`,
  "VfL Bochum": `${BASE}/36.png`,
  "Bochum": `${BASE}/36.png`,
  "1. FC Heidenheim 1846": `${BASE}/44.png`,
  "FC Heidenheim": `${BASE}/44.png`,
  "Heidenheim": `${BASE}/44.png`,
  "Holstein Kiel": `${BASE}/720.png`,
  "RB Leipzig": `${BASE}/721.png`,
  // ── Serie A ─────────────────────────────────────────────────────
  "AC Milan": `${BASE}/98.png`,
  "Milan": `${BASE}/98.png`,
  "ACF Fiorentina": `${BASE}/99.png`,
  "Fiorentina": `${BASE}/99.png`,
  "AS Roma": `${BASE}/100.png`,
  "Roma": `${BASE}/100.png`,
  "Atalanta BC": `${BASE}/102.png`,
  "Atalanta": `${BASE}/102.png`,
  "Bologna FC 1909": `${BASE}/103.png`,
  "Bologna": `${BASE}/103.png`,
  "Cagliari Calcio": `${BASE}/104.png`,
  "Cagliari": `${BASE}/104.png`,
  "Genoa CFC": `${BASE}/107.png`,
  "Genoa": `${BASE}/107.png`,
  "FC Internazionale Milano": `${BASE}/108.png`,
  "Internazionale": `${BASE}/108.png`,
  "Inter Milan": `${BASE}/108.png`,
  "Inter": `${BASE}/108.png`,
  "Juventus FC": `${BASE}/109.png`,
  "Juventus": `${BASE}/109.png`,
  "SS Lazio": `${BASE}/110.png`,
  "Lazio": `${BASE}/110.png`,
  "Parma Calcio 1913": `${BASE}/112.png`,
  "Parma": `${BASE}/112.png`,
  "SSC Napoli": `${BASE}/113.png`,
  "Napoli": `${BASE}/113.png`,
  "Udinese Calcio": `${BASE}/115.png`,
  "Udinese": `${BASE}/115.png`,
  "Empoli FC": `${BASE}/445.png`,
  "Empoli": `${BASE}/445.png`,
  "Hellas Verona FC": `${BASE}/450.png`,
  "Verona": `${BASE}/450.png`,
  "Venezia FC": `${BASE}/454.png`,
  "Venezia": `${BASE}/454.png`,
  "US Cremonese": `${BASE}/457.png`,
  "Cremonese": `${BASE}/457.png`,
  "US Sassuolo Calcio": `${BASE}/471.png`,
  "Sassuolo": `${BASE}/471.png`,
  "AC Pisa 1909": `${BASE}/487.png`,
  "Pisa": `${BASE}/487.png`,
  "Torino FC": `${BASE}/586.png`,
  "Torino": `${BASE}/586.png`,
  "US Lecce": `${BASE}/5890.png`,
  "Lecce": `${BASE}/5890.png`,
  "AC Monza": `${BASE}/5911.png`,
  "Monza": `${BASE}/5911.png`,
  "Como 1907": `${BASE}/7397.png`,
  "Como": `${BASE}/7397.png`,
  // ── Ligue 1 ─────────────────────────────────────────────────────
  "Toulouse FC": `${BASE}/511.png`,
  "Toulouse": `${BASE}/511.png`,
  "Stade Brestois 29": `${BASE}/512.png`,
  "Brest": `${BASE}/512.png`,
  "Olympique de Marseille": `${BASE}/516.png`,
  "Marseille": `${BASE}/516.png`,
  "Montpellier HSC": `${BASE}/518.png`,
  "Montpellier": `${BASE}/518.png`,
  "AJ Auxerre": `${BASE}/519.png`,
  "Auxerre": `${BASE}/519.png`,
  "Lille OSC": `${BASE}/521.png`,
  "LOSC Lille": `${BASE}/521.png`,
  "Lille": `${BASE}/521.png`,
  "OGC Nice": `${BASE}/522.png`,
  "Nice": `${BASE}/522.png`,
  "Olympique Lyonnais": `${BASE}/523.png`,
  "Lyon": `${BASE}/523.png`,
  "Paris Saint-Germain FC": `${BASE}/524.png`,
  "Paris Saint-Germain": `${BASE}/524.png`,
  "PSG": `${BASE}/524.png`,
  "FC Lorient": `${BASE}/525.png`,
  "Lorient": `${BASE}/525.png`,
  "AS Saint-Étienne": `${BASE}/527.png`,
  "Saint-Étienne": `${BASE}/527.png`,
  "Stade Rennais FC 1901": `${BASE}/529.png`,
  "Stade Rennais FC": `${BASE}/529.png`,
  "Rennes": `${BASE}/529.png`,
  "Angers SCO": `${BASE}/532.png`,
  "SCO Angers": `${BASE}/532.png`,
  "Angers": `${BASE}/532.png`,
  "Le Havre AC": `${BASE}/533.png`,
  "Le Havre": `${BASE}/533.png`,
  "FC Nantes": `${BASE}/543.png`,
  "Nantes": `${BASE}/543.png`,
  "FC Metz": `${BASE}/545.png`,
  "Metz": `${BASE}/545.png`,
  "Racing Club de Lens": `${BASE}/546.png`,
  "RC Lens": `${BASE}/546.png`,
  "Lens": `${BASE}/546.png`,
  "Stade de Reims": `${BASE}/547.png`,
  "Reims": `${BASE}/547.png`,
  "AS Monaco FC": `${BASE}/548.png`,
  "Monaco": `${BASE}/548.png`,
  "RC Strasbourg Alsace": `${BASE}/576.png`,
  "Strasbourg": `${BASE}/576.png`,
  "Paris FC": `${BASE}/1045.png`,
};

export function getTeamCrest(teamName) {
  if (!teamName) return null;
  return CRESTS[teamName] ?? null;
}
